name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker compose build dev
          docker compose run --rm dev composer install
          docker compose run --rm dev composer ci
