name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker compose build dev
          docker compose run --rm dev composer install
          docker compose run --rm \
            -e TESTS_QUERY_API_URL=${{ env.TESTS_QUERY_API_URL }} \ 
            -e TESTS_STORAGE_API_TOKEN={{ secrets.TESTS_STORAGE_API_TOKEN }} \ 
            dev composer ci
